### ISSUE TITLE
DataBlock isChanged is not correct

### ISSUE THREAD

**Issue by qyen** [onovotny/MiFare#3]
`MiFare.Classic.DataBlock` 

`public bool IsChanged => (!data.Equals(origData));`

is maybe 

`public bool IsChanged => (!data.SequenceEqual(origData));`

**Comment by clairernovotny** [comment]
To set expectations, I am not actively working on this project but will accept PR's and get new versions out if there are fixes.

**Comment by clairernovotny** [comment]
Fixed by #5
