### ISSUE TITLE
Missing condition/check regarding GetData()

### ISSUE THREAD

**Issue by f-israel** [onovotny/MiFare#4]
Guess this shouldn't be that way but trying to dump my card I stumpled over some bug.
Easy to replicate: (for shortening here I didn't use await)
`byte[] rawDataS0B0 = card.GetSector(sector).GetData(0).Result;
card.Flush().Wait();`
throws Exception "CardWriteException: Unable to write in sector 0, block 0".

Only guessing but every GetData also sets the blocks changed property to true? This would extremly shorten the lifespan. Please check into this. Not sure but could be related to [#3](https://github.com/onovotny/MiFare/issues/3)

**Comment by clairernovotny** [comment]
To set expectations, I am not actively working on this project but will accept PR's and get new versions out if there are fixes.

**Comment by clairernovotny** [comment]
Fixed by #5
